# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Basic"
license = "MIT"
licenselink = "https://github.com/siegerts/hugo-theme-basic/blob/master/LICENSE"
description = ""
homepage = "https://github.com/siegerts/hugo-theme-basic"
tags = []
features = []
min_version = "0.41"

[author]
  name = "S. Siegert"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
